//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTutorial
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogloszenie
    {
        public int Id { get; set; }
        public string Tytul { get; set; }
        public string Opis { get; set; }
        public int SprzedajacyID { get; set; }
        public decimal Cena { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
